#pragma once
#include <string>
#include <fstream>
#include <filesystem>

// Build-time embedded HTML (generated by cmake/embed_resource.cmake)
#include "studio_embedded.h"

namespace ariadne {

inline std::string load_studio_html() {
    // Dev mode: prefer file on disk (hot reload without rebuild)
    for (const auto& path : {"studio/index.html", "../studio/index.html"}) {
        if (std::filesystem::exists(path)) {
            std::ifstream f(path);
            return std::string(std::istreambuf_iterator<char>(f), {});
        }
    }
    // Release mode: use embedded data
    if (studio_html_size > 0) {
        return std::string(reinterpret_cast<const char*>(studio_html_data), studio_html_size);
    }
    return "<html><body><h1>Ariadne Studio</h1><p>UI not available.</p></body></html>";
}

} // namespace ariadne
